from matrixClass import matrix
from dotAdd import dotAdd
from dotProd import dotProd
from exponentiation import takeExponent
from getTrace import getDiagonalAndTrace
from matrixByMatrixMult import multMatrix
from scalarMult import scalarMult
from sparseMatrixEncoder import matrixToCode
from sparseMatrixEncoder import codeToMatrix
