from matrixClass import matrix
from dotAdd import dotAdd
from dotProd import dotProd
from exponentiation import takeExponent
from getTrace import getTrace
from getDiagonal import getDiagonal
from matrixByMatrixMult import matMul
from scalarMult import scalarMult
from sparseMatrixEncoder import matrixToCode
from sparseMatrixEncoder import codeToMatrix
from createIdentityMatrix import CreateIdentityMatrix
